### ISSUE TITLE
IDE support, ctrl-click to open file. instead of searching

### ISSUE THREAD

**Issue by linonetwo** [LinkedSoftwareDependencies/Components.js#144] opened 2024-08-20 08:45 UTC
#### Issue type:

- :heavy_plus_sign: Feature request 

____
#### Description:

My team is using this to develop a new Community Solid Server plugin. We find DX is bad because you can't click to open source file like typedi / inversify.js does.

But with a VSCode plugin, this may be possible.

Also there seem to be no JSONSchema check, which could be done by run TS-to-JSONSchema in the LSP.

**Comment by rubensworks** [comment] 2024-08-20 08:58
I fully agree with this :-)

The problem is just finding someone who is willing to implement this. (perhaps @ajuvercr?)

But I'm closing this issue here, as we have one open already on the same topic: #13 (which has been open for a while...)

**Closed by rubensworks** 2024-08-20 08:58 UTC
Labels: feature ➕
